### ISSUE TITLE
Could you release a checkpoint or give some suggestion about how to reproduce your result?

### ISSUE THREAD

**Issue by ghost** [AutoTemp/Shallow-Aggressive-Decoding#1]

**Comment by AutoTemp** [comment]
Before inference based on our codes, you should use fairseq to train a GEC seq2seq model which is similar with training a translation model (You can refer to https://github.com/pytorch/fairseq/blob/master/examples/translation/README.md):
   1. preprocess sentence using BPE or sentencepiece
   2. binarize the dataset
   3. train the model

The common training dataset is BEA-19. You can refer to https://github.com/sebastianruder/NLP-progress/blob/master/english/grammatical_error_correction.md

**Comment by ghost** [comment]
> 
> 
> Before inference based on our codes, you should use fairseq to train a GEC seq2seq model which is similar with training a translation model (You can refer to https://github.com/pytorch/fairseq/blob/master/examples/translation/README.md):
> 
>     1. preprocess sentence using BPE or sentencepiece
> 
>     2. binarize the dataset
> 
>     3. train the model
> 
> 
> The common training dataset is BEA-19. You can refer to https://github.com/sebastianruder/NLP-progress/blob/master/english/grammatical_error_correction.md

Thanks for your suggestion. However, I see you using a (12 + 2) BART for training, is this code released ?

**Comment by AutoTemp** [comment]
> > Before inference based on our codes, you should use fairseq to train a GEC seq2seq model which is similar with training a translation model (You can refer to https://github.com/pytorch/fairseq/blob/master/examples/translation/README.md):
> > ```
> > 1. preprocess sentence using BPE or sentencepiece
> > 
> > 2. binarize the dataset
> > 
> > 3. train the model
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The common training dataset is BEA-19. You can refer to https://github.com/sebastianruder/NLP-progress/blob/master/english/grammatical_error_correction.md
> 
> Thanks for your suggestion. However, I see you using a (12 + 2) BART for training, is this code released ?


You can refer to https://github.com/pytorch/fairseq/blob/main/examples/bart/README.summarization.md
and combine "--encoder-layers-to-keep and --decoder-layers-to-keep"
