### ISSUE TITLE
Could you release some resource for Chinese GEC?

### ISSUE THREAD

**Issue by Yang-HangWA** [AutoTemp/Shallow-Aggressive-Decoding#2]
In your paper, I see some work on Chinese GEC.  Can you release some resources for this?

**Comment by AutoTemp** [comment]
You can refer to this [link](http://tcci.ccf.org.cn/conference/2018/taskdata.php) which contains guidelines and data of NLPCC2018 Shared Task2 -- Grammatical Error Correction.
