### ISSUE TITLE
Preprocessing scripts for Chinese GEC

### ISSUE THREAD

**Issue by MichaelCaohn** [AutoTemp/Shallow-Aggressive-Decoding#3]
Hi Authors,

Thank you very much for the work and for making the code public.

I have noticed that you have trained and evaluated the model on the NLPCC-2018 task. I am a bit curious about how did you preprocess the data. 

Therefore, would you mind sharing some details like what are the steps we need to carry out to preprocess the data? how did you create the vocabulary? how did you tokenize the training data, etc.

Thank you!

**Comment by AutoTemp** [comment]
As mentioned in the paper, we tokenize the training data in character-level and create the vocabulary with 8.4K Chinese characters. 
After inference in character-level, we tokenize the results by the PKUNLP tool.

**Comment by MichaelCaohn** [comment]
Hi authors, 

Thank you very much for the prompt reply:)

I have some more questions about it.

Would you mind sharing the 8.4k vocabulary or maybe the character-level tokenization script used in the experiment?

DId you apply BPE to the training sentence after the character level tokenization has been applied?

Also, would you mind providing a link to the PKUNLP tool that you have used? I referred to the PKUNLP tool provided in NLPCC-2018 Shared Task's Github (https://github.com/zhaoyyoo/NLPCC2018_GEC), it seems the link to the PKUNLP tool is expired. 

Thank you!

**Comment by AutoTemp** [comment]
We just apply the character level tokenization (' '.join(list(sentence))) and do not apply BPE for Chinese data.  
I sent PKUNLP to your gmail.

**Comment by MichaelCaohn** [comment]
Thank you very much!

**Comment by MichaelCaohn** [comment]
Hi authors,

Thank you for providing the information. I managed to apply character level tokenization with " ".join(list(sentence)), and pass this tokenized into fairseq-preprocess command to generate the vocabulary.  However, instead of getting a vocabulary of 8.4K, it returned me a vocabulary of 400, and the <UNK> percentage is around 40%. It seems not correct.

May I know how did you generate the 8.4K vocabulary?

Thank you

**Comment by MichaelCaohn** [comment]
The fairseq-preprocess command I am using is: 

fairseq-preprocess --source-lang src --target-lang tgt \
        --trainpref $PROCESSED_DIR/train \
        --validpref $PROCESSED_DIR/valid \
        --destdir "$PROCESSED_DIR-bin" \
        --workers $cpu_num \
        --thresholdsrc 90000 \
        --thresholdtgt 90000 \
        --joined-dictionary

**Comment by AutoTemp** [comment]
We do not use 'thresholdsrc' and 'thresholdtgt', which mean drop words appearing less than the threshold. 
You can refer to the tutorial to learn how to use fairseq.

**Comment by liangjinggui** [comment]
Hi authors,
would you mind providing a link to the PKUNLP tool that you have used? I referred to the PKUNLP tool provided in NLPCC-2018 Shared Task's Github (https://github.com/zhaoyyoo/NLPCC2018_GEC), it seems the link to the PKUNLP tool is expired.

Thank you!
