### ISSUE TITLE
Question about PKUNLP segment tool

### ISSUE THREAD

**Issue by liangjinggui** [AutoTemp/Shallow-Aggressive-Decoding#4]
Hi authors,
would you mind providing a link to the PKUNLP tool that you have used? I referred to the PKUNLP tool provided in NLPCC-2018 Shared Task's Github (https://github.com/zhaoyyoo/NLPCC2018_GEC), it seems the link to the PKUNLP tool is expired.

Thank you!

**Comment by AutoTemp** [comment]
Your email?

**Comment by liangjinggui** [comment]
> 

jingguiliang@gmail.com Thank you so much!
